# Use a base image with Java runtime
FROM openjdk:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the target directory to the image
COPY target/spring-boot-2-hello-world-1.0.2-SNAPSHOT.jar /app/app.jar 

# Set the entry point to run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
